CREATE TABLE IF NOT EXISTS  STUFF (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR (255) NOT NULL,
    COST FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS APP_USER (
    ID   INT PRIMARY KEY AUTO_INCREMENT,
    USER_NAME VARCHAR(256) NOT NULL,
    EMAIL VARCHAR(256) NOT NULL,
    PSWD VARCHAR(256) NOT NULL
);