CREATE TABLE IF NOT EXISTS APP_USER
(
    ID       SERIAL,
    USERNAME VARCHAR(256) NOT NULL,
    EMAIL    VARCHAR(256) NOT NULL,
    PSWD     VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS STUFF
(
    ID          SERIAL,
    NAME        VARCHAR(255)   NOT NULL,
    BRAND       VARCHAR(255)   NOT NULL,
    DESCRIPTION VARCHAR(1024)  NOT NULL,
    COST        DECIMAL(19, 2) NOT NULL,
    PICTURE     LONGBLOB       NOT NULL,
    USER_ID     INT REFERENCES APP_USER (ID)
);

CREATE TABLE IF NOT EXISTS RESET_PASSWORD
(
    ID   VARCHAR(36) PRIMARY KEY,
    USER_ID INT REFERENCES APP_USER (ID)
);
