<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%--CSS--%>
<link rel="stylesheet" href="<c:url value="/resources/css/bootstrap.min.css" />">
<link rel="stylesheet" href="<c:url value="/resources/css/main.css" />">
<%--FAVICON--%>
<link href="data:image/x-icon;base64,AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAjGM6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARERERERERABEREREREREAEREREREREQARAAAAAAARABEAAAAAABEAEREREREAEQAREREREQARABEAAAAAABEAEQAAAAAAEQARABERERERABEAEREREREAEQAAAAAAEQARAAAAAAARABEREREREREAEREREREREQARERERERERCAAQAAgAEAAIABAACf+QAAn/kAAIAZAACAGQAAn/kAAJ/5AACYAQAAmAEAAJ/5AACf+QAAgAEAAIABAACAAQAA"
      rel="icon" type="image/x-icon"/>